import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Anek_Latin } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const anek = Anek_Latin({ subsets: ['latin'] })

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "BlogVerse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={anek.className}>{children}</body>
    </html>
    </ClerkProvider>
    
  );
}
